/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait DefaultApi: Send + Sync {
    /// GET /api/v1/clients/{clientId}/bundles/{digest}
    ///
    ///
    async fn api_v1_clients_client_id_bundles_digest_get<'client_id, 'digest, 'if_none_match>(
        &self,
        client_id: &'client_id str,
        digest: &'digest str,
        if_none_match: Option<&'if_none_match str>,
    ) -> Result<std::path::PathBuf, Error<ApiV1ClientsClientIdBundlesDigestGetError>>;

    /// POST /api/v1/clients/{clientId}/capabilities
    ///
    ///
    async fn api_v1_clients_client_id_capabilities_post<'client_id, 'device_capabilities_manifest>(
        &self,
        client_id: &'client_id str,
        device_capabilities_manifest: models::DeviceCapabilitiesManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPostError>>;

    /// PUT /api/v1/clients/{clientId}/capabilities
    ///
    ///
    async fn api_v1_clients_client_id_capabilities_put<'client_id, 'device_capabilities_manifest>(
        &self,
        client_id: &'client_id str,
        device_capabilities_manifest: models::DeviceCapabilitiesManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPutError>>;

    /// POST /api/v1/clients/{clientId}/deployment/{deploymentId}/status
    ///
    ///
    async fn api_v1_clients_client_id_deployment_deployment_id_status_post<
        'client_id,
        'deployment_id,
        'deployment_status_manifest,
    >(
        &self,
        client_id: &'client_id str,
        deployment_id: &'deployment_id str,
        deployment_status_manifest: models::DeploymentStatusManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError>>;

    /// GET /api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}
    ///
    /// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
    async fn api_v1_clients_client_id_deployments_deployment_id_digest_get<
        'client_id,
        'deployment_id,
        'digest,
        'if_none_match,
        'accept_encoding,
    >(
        &self,
        client_id: &'client_id str,
        deployment_id: &'deployment_id str,
        digest: &'digest str,
        if_none_match: Option<&'if_none_match str>,
        accept_encoding: Option<&'accept_encoding str>,
    ) -> Result<String, Error<ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError>>;

    /// GET /api/v1/clients/{clientId}/deployments
    ///
    ///
    async fn api_v1_clients_client_id_deployments_get<'client_id, 'if_none_match, 'accept>(
        &self,
        client_id: &'client_id str,
        if_none_match: Option<&'if_none_match str>,
        accept: Option<&'accept str>,
    ) -> Result<models::UnsignedAppStateManifest, Error<ApiV1ClientsClientIdDeploymentsGetError>>;

    /// GET /api/v1/onboarding/certificate
    ///
    ///
    async fn api_v1_onboarding_certificate_get(
        &self,
    ) -> Result<
        models::ApiV1OnboardingCertificateGet200Response,
        Error<ApiV1OnboardingCertificateGetError>,
    >;

    /// POST /api/v1/onboarding
    ///
    ///
    async fn api_v1_onboarding_post<'api_v1_onboarding_post_request>(
        &self,
        api_v1_onboarding_post_request: models::ApiV1OnboardingPostRequest,
    ) -> Result<models::ApiV1OnboardingPost201Response, Error<ApiV1OnboardingPostError>>;
}

pub struct DefaultApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DefaultApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl DefaultApi for DefaultApiClient {
    async fn api_v1_clients_client_id_bundles_digest_get<'client_id, 'digest, 'if_none_match>(
        &self,
        client_id: &'client_id str,
        digest: &'digest str,
        if_none_match: Option<&'if_none_match str>,
    ) -> Result<std::path::PathBuf, Error<ApiV1ClientsClientIdBundlesDigestGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/bundles/{digest}",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id),
            digest = crate::apis::urlencode(digest)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = if_none_match {
            local_var_req_builder =
                local_var_req_builder.header("If-None-Match", local_var_param_value.to_string());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1ClientsClientIdBundlesDigestGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_clients_client_id_capabilities_post<
        'client_id,
        'device_capabilities_manifest,
    >(
        &self,
        client_id: &'client_id str,
        device_capabilities_manifest: models::DeviceCapabilitiesManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/capabilities",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&device_capabilities_manifest);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ApiV1ClientsClientIdCapabilitiesPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_clients_client_id_capabilities_put<
        'client_id,
        'device_capabilities_manifest,
    >(
        &self,
        client_id: &'client_id str,
        device_capabilities_manifest: models::DeviceCapabilitiesManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPutError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/capabilities",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&device_capabilities_manifest);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ApiV1ClientsClientIdCapabilitiesPutError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_clients_client_id_deployment_deployment_id_status_post<
        'client_id,
        'deployment_id,
        'deployment_status_manifest,
    >(
        &self,
        client_id: &'client_id str,
        deployment_id: &'deployment_id str,
        deployment_status_manifest: models::DeploymentStatusManifest,
    ) -> Result<(), Error<ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/deployment/{deploymentId}/status",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id),
            deploymentId = crate::apis::urlencode(deployment_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&deployment_status_manifest);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<
                ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError,
            > = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
    async fn api_v1_clients_client_id_deployments_deployment_id_digest_get<
        'client_id,
        'deployment_id,
        'digest,
        'if_none_match,
        'accept_encoding,
    >(
        &self,
        client_id: &'client_id str,
        deployment_id: &'deployment_id str,
        digest: &'digest str,
        if_none_match: Option<&'if_none_match str>,
        accept_encoding: Option<&'accept_encoding str>,
    ) -> Result<String, Error<ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id),
            deploymentId = crate::apis::urlencode(deployment_id),
            digest = crate::apis::urlencode(digest)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = if_none_match {
            local_var_req_builder =
                local_var_req_builder.header("If-None-Match", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = accept_encoding {
            local_var_req_builder =
                local_var_req_builder.header("Accept-Encoding", local_var_param_value.to_string());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `String`")))),
            }
        } else {
            let local_var_entity: Option<
                ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError,
            > = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_clients_client_id_deployments_get<'client_id, 'if_none_match, 'accept>(
        &self,
        client_id: &'client_id str,
        if_none_match: Option<&'if_none_match str>,
        accept: Option<&'accept str>,
    ) -> Result<models::UnsignedAppStateManifest, Error<ApiV1ClientsClientIdDeploymentsGetError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/clients/{clientId}/deployments",
            local_var_configuration.base_path,
            clientId = crate::apis::urlencode(client_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = if_none_match {
            local_var_req_builder =
                local_var_req_builder.header("If-None-Match", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = accept {
            local_var_req_builder =
                local_var_req_builder.header("Accept", local_var_param_value.to_string());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnsignedAppStateManifest`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UnsignedAppStateManifest`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1ClientsClientIdDeploymentsGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_onboarding_certificate_get(
        &self,
    ) -> Result<
        models::ApiV1OnboardingCertificateGet200Response,
        Error<ApiV1OnboardingCertificateGetError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/onboarding/certificate",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApiV1OnboardingCertificateGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ApiV1OnboardingCertificateGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1OnboardingCertificateGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_onboarding_post<'api_v1_onboarding_post_request>(
        &self,
        api_v1_onboarding_post_request: models::ApiV1OnboardingPostRequest,
    ) -> Result<models::ApiV1OnboardingPost201Response, Error<ApiV1OnboardingPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/onboarding", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder =
                local_var_req_builder.header("X-Payload-Signature", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&api_v1_onboarding_post_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApiV1OnboardingPost201Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ApiV1OnboardingPost201Response`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1OnboardingPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_bundles_digest_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdBundlesDigestGetError {
    Status404(),
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_capabilities_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdCapabilitiesPostError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_capabilities_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdCapabilitiesPutError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_deployment_deployment_id_status_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_deployments_deployment_id_digest_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_clients_client_id_deployments_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentsGetError {
    Status406(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_onboarding_certificate_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1OnboardingCertificateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DefaultApi::api_v1_onboarding_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1OnboardingPostError {
    Status400(models::ApiV1OnboardingPost400Response),
    Status403(models::ApiV1OnboardingPost403Response),
    UnknownValue(serde_json::Value),
}
