/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`api_v1_clients_client_id_bundles_digest_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdBundlesDigestGetError {
    Status404(),
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_clients_client_id_capabilities_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdCapabilitiesPostError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_clients_client_id_capabilities_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdCapabilitiesPutError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_clients_client_id_deployment_deployment_id_status_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError {
    Status400(),
    Status401(),
    Status403(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_clients_client_id_deployments_deployment_id_digest_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_clients_client_id_deployments_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ClientsClientIdDeploymentsGetError {
    Status406(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_onboarding_certificate_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1OnboardingCertificateGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_onboarding_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1OnboardingPostError {
    Status400(models::ApiV1OnboardingPost400Response),
    Status403(models::ApiV1OnboardingPost403Response),
    UnknownValue(serde_json::Value),
}

pub async fn api_v1_clients_client_id_bundles_digest_get(
    configuration: &configuration::Configuration,
    client_id: &str,
    digest: &str,
    if_none_match: Option<&str>,
) -> Result<reqwest::Response, Error<ApiV1ClientsClientIdBundlesDigestGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_path_digest = digest;
    let p_header_if_none_match = if_none_match;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/bundles/{digest}",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id),
        digest = crate::apis::urlencode(p_path_digest)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_if_none_match {
        req_builder = req_builder.header("If-None-Match", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdBundlesDigestGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_clients_client_id_capabilities_post(
    configuration: &configuration::Configuration,
    client_id: &str,
    device_capabilities_manifest: models::DeviceCapabilitiesManifest,
) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_body_device_capabilities_manifest = device_capabilities_manifest;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/capabilities",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };
    req_builder = req_builder.json(&p_body_device_capabilities_manifest);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdCapabilitiesPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_clients_client_id_capabilities_put(
    configuration: &configuration::Configuration,
    client_id: &str,
    device_capabilities_manifest: models::DeviceCapabilitiesManifest,
) -> Result<(), Error<ApiV1ClientsClientIdCapabilitiesPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_body_device_capabilities_manifest = device_capabilities_manifest;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/capabilities",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };
    req_builder = req_builder.json(&p_body_device_capabilities_manifest);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdCapabilitiesPutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_clients_client_id_deployment_deployment_id_status_post(
    configuration: &configuration::Configuration,
    client_id: &str,
    deployment_id: &str,
    deployment_status_manifest: models::DeploymentStatusManifest,
) -> Result<(), Error<ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_path_deployment_id = deployment_id;
    let p_body_deployment_status_manifest = deployment_status_manifest;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/deployment/{deploymentId}/status",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id),
        deploymentId = crate::apis::urlencode(p_path_deployment_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };
    req_builder = req_builder.json(&p_body_deployment_status_manifest);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdDeploymentDeploymentIdStatusPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// This endpoint is used by the client to fetch the YAML for a single ApplicationDeployment after it has processed a new State Manifest and identified a small number of new or updated deployments. This allows for highly efficient, incremental updates without needing to download the full bundle. To make individual workload retrievals race-free and cache-friendly, this endpoint is content-addressable: the digest of the expected YAML is part of the URL. This guarantees immutability of the fetched resource and prevents a time-of-check / time-of-use race where a deployment changes between manifest retrieval and content fetch.
pub async fn api_v1_clients_client_id_deployments_deployment_id_digest_get(
    configuration: &configuration::Configuration,
    client_id: &str,
    deployment_id: &str,
    digest: &str,
    if_none_match: Option<&str>,
    accept_encoding: Option<&str>,
) -> Result<String, Error<ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_path_deployment_id = deployment_id;
    let p_path_digest = digest;
    let p_header_if_none_match = if_none_match;
    let p_header_accept_encoding = accept_encoding;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/deployments/{deploymentId}/{digest}",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id),
        deploymentId = crate::apis::urlencode(p_path_deployment_id),
        digest = crate::apis::urlencode(p_path_digest)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_if_none_match {
        req_builder = req_builder.header("If-None-Match", param_value.to_string());
    }
    if let Some(param_value) = p_header_accept_encoding {
        req_builder = req_builder.header("Accept-Encoding", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdDeploymentsDeploymentIdDigestGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_clients_client_id_deployments_get(
    configuration: &configuration::Configuration,
    client_id: &str,
    if_none_match: Option<&str>,
    accept: Option<&str>,
) -> Result<models::UnsignedAppStateManifest, Error<ApiV1ClientsClientIdDeploymentsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_client_id = client_id;
    let p_header_if_none_match = if_none_match;
    let p_header_accept = accept;

    let uri_str = format!(
        "{}/api/v1/clients/{clientId}/deployments",
        configuration.base_path,
        clientId = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_if_none_match {
        req_builder = req_builder.header("If-None-Match", param_value.to_string());
    }
    if let Some(param_value) = p_header_accept {
        req_builder = req_builder.header("Accept", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UnsignedAppStateManifest`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UnsignedAppStateManifest`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ClientsClientIdDeploymentsGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_onboarding_certificate_get(
    configuration: &configuration::Configuration,
) -> Result<
    models::ApiV1OnboardingCertificateGet200Response,
    Error<ApiV1OnboardingCertificateGetError>,
> {
    let uri_str = format!("{}/api/v1/onboarding/certificate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApiV1OnboardingCertificateGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApiV1OnboardingCertificateGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1OnboardingCertificateGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_onboarding_post(
    configuration: &configuration::Configuration,
    api_v1_onboarding_post_request: models::ApiV1OnboardingPostRequest,
) -> Result<models::ApiV1OnboardingPost201Response, Error<ApiV1OnboardingPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_api_v1_onboarding_post_request = api_v1_onboarding_post_request;

    let uri_str = format!("{}/api/v1/onboarding", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Payload-Signature", value);
    };
    req_builder = req_builder.json(&p_body_api_v1_onboarding_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApiV1OnboardingPost201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApiV1OnboardingPost201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1OnboardingPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
