/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1OnboardingPostRequest {
    /// API version identifier
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    /// Resource kind
    #[serde(rename = "kind")]
    pub kind: Kind,
    /// Base64-encoded client certificate
    #[serde(rename = "certificate")]
    pub certificate: String,
}

impl ApiV1OnboardingPostRequest {
    pub fn new(api_version: String, kind: Kind, certificate: String) -> ApiV1OnboardingPostRequest {
        ApiV1OnboardingPostRequest {
            api_version,
            kind,
            certificate,
        }
    }
}
/// Resource kind
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "OnboardingRequest")]
    OnboardingRequest,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::OnboardingRequest
    }
}
