/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppDeploymentSpec : Application Deployment specification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppDeploymentSpec {
    #[serde(rename = "deploymentProfile")]
    pub deployment_profile: Box<models::AppDeploymentProfile>,
    /// Application Parameters
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, models::AppParameterValue>>,
}

impl AppDeploymentSpec {
    /// Application Deployment specification
    pub fn new(deployment_profile: models::AppDeploymentProfile) -> AppDeploymentSpec {
        AppDeploymentSpec {
            deployment_profile: Box::new(deployment_profile),
            parameters: None,
        }
    }
}
