/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppDeploymentManifest : Application Deployment manifest
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppDeploymentManifest {
    /// API version
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    /// Resource kind
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::AppDeploymentMetadata>,
    #[serde(rename = "spec")]
    pub spec: Box<models::AppDeploymentSpec>,
}

impl AppDeploymentManifest {
    /// Application Deployment manifest
    pub fn new(
        api_version: String,
        kind: String,
        metadata: models::AppDeploymentMetadata,
        spec: models::AppDeploymentSpec,
    ) -> AppDeploymentManifest {
        AppDeploymentManifest {
            api_version,
            kind,
            metadata: Box::new(metadata),
            spec: Box::new(spec),
        }
    }
}
