/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppParameterValue : Application Parameter Value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppParameterValue {
    /// Value of the parameter
    #[serde(rename = "value")]
    pub value: serde_json::Value,
    /// Targets of the parameter
    #[serde(rename = "targets")]
    pub targets: Vec<models::AppParameterTarget>,
}

impl AppParameterValue {
    /// Application Parameter Value
    pub fn new(
        value: serde_json::Value,
        targets: Vec<models::AppParameterTarget>,
    ) -> AppParameterValue {
        AppParameterValue { value, targets }
    }
}
