/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AppDeploymentProfileComponentsInner {
    HelmApplicationDeploymentProfileComponent(
        Box<models::HelmApplicationDeploymentProfileComponent>,
    ),
    ComposeApplicationDeploymentProfileComponent(
        Box<models::ComposeApplicationDeploymentProfileComponent>,
    ),
}

impl Default for AppDeploymentProfileComponentsInner {
    fn default() -> Self {
        Self::HelmApplicationDeploymentProfileComponent(Default::default())
    }
}
