/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppParameterTarget : Application Parameter Target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppParameterTarget {
    /// Pointer to the parameter
    #[serde(rename = "pointer")]
    pub pointer: String,
    /// Components of the parameter
    #[serde(rename = "components")]
    pub components: Vec<String>,
}

impl AppParameterTarget {
    /// Application Parameter Target
    pub fn new(pointer: String, components: Vec<String>) -> AppParameterTarget {
        AppParameterTarget {
            pointer,
            components,
        }
    }
}
