/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppDeploymentProfile : Application Deployment Profile
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppDeploymentProfile {
    /// Type of deployment profile
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Components of the deployment profile
    #[serde(rename = "components")]
    pub components: Vec<models::AppDeploymentProfileComponentsInner>,
}

impl AppDeploymentProfile {
    /// Application Deployment Profile
    pub fn new(
        r#type: Type,
        components: Vec<models::AppDeploymentProfileComponentsInner>,
    ) -> AppDeploymentProfile {
        AppDeploymentProfile { r#type, components }
    }
}
/// Type of deployment profile
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "helm.v3")]
    HelmV3,
    #[serde(rename = "compose")]
    Compose,
}

impl Default for Type {
    fn default() -> Type {
        Self::HelmV3
    }
}
