/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentStatus {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::ComponentStatusError>>,
}

impl ComponentStatus {
    pub fn new(name: String, state: State) -> ComponentStatus {
        ComponentStatus {
            name,
            state,
            error: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Installing")]
    Installing,
    #[serde(rename = "Installed")]
    Installed,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Removing")]
    Removing,
    #[serde(rename = "Removed")]
    Removed,
    #[serde(rename = "Updating")]
    Updating,
    #[serde(rename = "Updated")]
    Updated,
}

impl Default for State {
    fn default() -> State {
        Self::Pending
    }
}
