/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeApplicationDeploymentProfileComponentProperties {
    /// Package location of the component
    #[serde(rename = "packageLocation")]
    pub package_location: String,
    /// Key location of the component
    #[serde(rename = "keyLocation", skip_serializing_if = "Option::is_none")]
    pub key_location: Option<String>,
    /// Timeout for the component
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    /// Wait for the component to be ready
    #[serde(rename = "wait", skip_serializing_if = "Option::is_none")]
    pub wait: Option<bool>,
}

impl ComposeApplicationDeploymentProfileComponentProperties {
    pub fn new(package_location: String) -> ComposeApplicationDeploymentProfileComponentProperties {
        ComposeApplicationDeploymentProfileComponentProperties {
            package_location,
            key_location: None,
            timeout: None,
            wait: None,
        }
    }
}
