/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentStatusManifest {
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "deploymentId")]
    pub deployment_id: String,
    #[serde(rename = "status")]
    pub status: Box<models::DeploymentStatusManifestStatus>,
    #[serde(rename = "components")]
    pub components: Vec<models::ComponentStatus>,
}

impl DeploymentStatusManifest {
    pub fn new(
        api_version: String,
        kind: Kind,
        deployment_id: String,
        status: models::DeploymentStatusManifestStatus,
        components: Vec<models::ComponentStatus>,
    ) -> DeploymentStatusManifest {
        DeploymentStatusManifest {
            api_version,
            kind,
            deployment_id,
            status: Box::new(status),
            components,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "DeploymentStatus")]
    DeploymentStatus,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::DeploymentStatus
    }
}
