/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentManifestRef : Reference to a deployment manifest with content addressing and integrity verification.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentManifestRef {
    /// The unique UUID from the ApplicationDeployment's metadata.annotations.id.
    #[serde(rename = "deploymentId")]
    pub deployment_id: String,
    /// The digest of the individual ApplicationDeployment YAML file. MUST equal the digest computed over the exact sequence of bytes (per Exact Bytes Rule) in that deployment endpoint's HTTP 200 OK response body.
    #[serde(rename = "digest")]
    pub digest: String,
    /// Unsigned 64-bit advisory estimate of the decoded payload length in bytes for the deployment YAML. Provided for planning or progress display. MUST NOT be used for integrity; digest verification remains mandatory.
    #[serde(rename = "sizeBytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<f64>,
    /// Content-addressable endpoint of the form /api/v1/devices/{deviceId}/deployments/{deploymentId}/{digest}. The {digest} MUST equal deployments[].digest; the referenced resource is immutable
    #[serde(rename = "url")]
    pub url: String,
}

impl DeploymentManifestRef {
    /// Reference to a deployment manifest with content addressing and integrity verification.
    pub fn new(deployment_id: String, digest: String, url: String) -> DeploymentManifestRef {
        DeploymentManifestRef {
            deployment_id,
            digest,
            size_bytes: None,
            url,
        }
    }
}
