/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCapabilitiesManifestPropertiesResourcesCpu {
    #[serde(rename = "cores", skip_serializing_if = "Option::is_none")]
    pub cores: Option<f64>,
}

impl DeviceCapabilitiesManifestPropertiesResourcesCpu {
    pub fn new() -> DeviceCapabilitiesManifestPropertiesResourcesCpu {
        DeviceCapabilitiesManifestPropertiesResourcesCpu { cores: None }
    }
}
