/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCommunicationInterface {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DeviceCommunicationInterface {
    pub fn new(r#type: Type) -> DeviceCommunicationInterface {
        DeviceCommunicationInterface { r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ethernet")]
    Ethernet,
    #[serde(rename = "wifi")]
    Wifi,
    #[serde(rename = "cellular")]
    Cellular,
    #[serde(rename = "bluetooth")]
    Bluetooth,
    #[serde(rename = "usb")]
    Usb,
    #[serde(rename = "canbus")]
    Canbus,
    #[serde(rename = "rs232")]
    Rs232,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ethernet
    }
}
