/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCapabilitiesManifestProperties {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "vendor")]
    pub vendor: String,
    #[serde(rename = "modelNumber")]
    pub model_number: String,
    #[serde(rename = "serialNumber")]
    pub serial_number: String,
    #[serde(rename = "roles")]
    pub roles: Vec<Roles>,
    #[serde(rename = "resources")]
    pub resources: Box<models::DeviceCapabilitiesManifestPropertiesResources>,
}

impl DeviceCapabilitiesManifestProperties {
    pub fn new(
        id: String,
        vendor: String,
        model_number: String,
        serial_number: String,
        roles: Vec<Roles>,
        resources: models::DeviceCapabilitiesManifestPropertiesResources,
    ) -> DeviceCapabilitiesManifestProperties {
        DeviceCapabilitiesManifestProperties {
            id,
            vendor,
            model_number,
            serial_number,
            roles,
            resources: Box::new(resources),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Roles {
    #[serde(rename = "Standalone Cluster")]
    StandaloneCluster,
    #[serde(rename = "Cluster Leader")]
    ClusterLeader,
    #[serde(rename = "Standalone Device")]
    StandaloneDevice,
}

impl Default for Roles {
    fn default() -> Roles {
        Self::StandaloneCluster
    }
}
