/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCapabilitiesManifestPropertiesResourcesCpu {
    #[serde(rename = "cores")]
    pub cores: f64,
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<Architecture>,
}

impl DeviceCapabilitiesManifestPropertiesResourcesCpu {
    pub fn new(cores: f64) -> DeviceCapabilitiesManifestPropertiesResourcesCpu {
        DeviceCapabilitiesManifestPropertiesResourcesCpu {
            cores,
            architecture: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Architecture {
    #[serde(rename = "amd64")]
    Amd64,
    #[serde(rename = "x86_64")]
    X8664,
    #[serde(rename = "arm64")]
    Arm64,
    #[serde(rename = "arm")]
    Arm,
}

impl Default for Architecture {
    fn default() -> Architecture {
        Self::Amd64
    }
}
