/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceCapabilitiesManifestPropertiesResources {
    #[serde(rename = "cpu")]
    pub cpu: Box<models::DeviceCapabilitiesManifestPropertiesResourcesCpu>,
    #[serde(rename = "memory")]
    pub memory: String,
    #[serde(rename = "storage")]
    pub storage: String,
}

impl DeviceCapabilitiesManifestPropertiesResources {
    pub fn new(
        cpu: models::DeviceCapabilitiesManifestPropertiesResourcesCpu,
        memory: String,
        storage: String,
    ) -> DeviceCapabilitiesManifestPropertiesResources {
        DeviceCapabilitiesManifestPropertiesResources {
            cpu: Box::new(cpu),
            memory,
            storage,
        }
    }
}
