/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelmApplicationDeploymentProfileComponentProperties {
    /// Repository of the component
    #[serde(rename = "repository")]
    pub repository: String,
    /// Revision of the component
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    /// Timeout for the component
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    /// Wait for the component to be ready
    #[serde(rename = "wait", skip_serializing_if = "Option::is_none")]
    pub wait: Option<bool>,
}

impl HelmApplicationDeploymentProfileComponentProperties {
    pub fn new(repository: String) -> HelmApplicationDeploymentProfileComponentProperties {
        HelmApplicationDeploymentProfileComponentProperties {
            repository,
            revision: None,
            timeout: None,
            wait: None,
        }
    }
}
