/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HelmApplicationDeploymentProfileComponent : Helm Application Deployment Profile Component
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelmApplicationDeploymentProfileComponent {
    /// Name of the component
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "properties")]
    pub properties: Box<models::HelmApplicationDeploymentProfileComponentProperties>,
}

impl HelmApplicationDeploymentProfileComponent {
    /// Helm Application Deployment Profile Component
    pub fn new(
        name: String,
        properties: models::HelmApplicationDeploymentProfileComponentProperties,
    ) -> HelmApplicationDeploymentProfileComponent {
        HelmApplicationDeploymentProfileComponent {
            name,
            properties: Box::new(properties),
        }
    }
}
