/*
 * Margo Workload Management API
 *
 * API for managing workloads on Margo-compliant edge devices. Includes the APIs for exchanging desired state and current state. Communication is secured using server-side TLS (TLS 1.3 preferred), and payloads are signed using X.509 certificates.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnsignedAppStateManifest {
    /// Monotonically increasing unsigned 64-bit integer in the inclusive range [1, 2^64-1]. Prevents rollback attacks. The first manifest MUST use 1.
    #[serde(rename = "manifestVersion")]
    pub manifest_version: f64,
    #[serde(rename = "bundle", deserialize_with = "Option::deserialize")]
    pub bundle: Option<Box<models::DeploymentBundleRef>>,
    /// A list of deployment object references for the device. The reference contains some meta info and reference to the url where the deployment is available.
    #[serde(rename = "deployments")]
    pub deployments: Vec<models::DeploymentManifestRef>,
}

impl UnsignedAppStateManifest {
    pub fn new(
        manifest_version: f64,
        bundle: Option<models::DeploymentBundleRef>,
        deployments: Vec<models::DeploymentManifestRef>,
    ) -> UnsignedAppStateManifest {
        UnsignedAppStateManifest {
            manifest_version,
            bundle: if let Some(x) = bundle {
                Some(Box::new(x))
            } else {
                None
            },
            deployments,
        }
    }
}
